universe   = docker
docker_image = vdiaz4318/final_project:perturbed
executable = run_model.sh

arguments = $(csv_file)

transfer_input_files = p_rand_forest.py, run_model.sh, WindFarmA_combined.csv, WindFarmB_combined.csv, WindFarmC_combined.csv

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = logs/$(Cluster)_$(Process).out
error  = logs/$(Cluster)_$(Process).err
log    = logs/$(Cluster).log

request_cpus = 1
request_memory = 20GB
request_disk = 20GB

queue csv_file from csv_list.txt

